apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "tenant-isolation"
spec:
  description: "enable multi tenant network policy"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/managed-by: tidb-operator
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/component: tidb
      toPorts:
        - ports:
            - port: "20160"
              protocol: TCP
            - port: "10261"
              protocol: TCP
            - port: "10080"
              protocol: TCP
          rules:
            l7proto: tidb
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/component: pd
      toPorts:
        - ports:
            - port: "20160"
              protocol: TCP
            - port: "10261"
              protocol: TCP
            - port: "2379"
              protocol: TCP
            - port: "10080"
              protocol: TCP
          rules:
            l7proto: tidb
